[package]
name = "acala-node"
authors = ["Acala Developers"]
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = { version = "0.6.3", default-features = false }

# TODO: update to a released version once available
polkadot-parachain-lib = { git = "https://github.com/serban300/polkadot-sdk", branch = "polkadot-parachain-lib" }
sc-chain-spec = { git = "https://github.com/serban300/polkadot-sdk", branch = "polkadot-parachain-lib" }
sc-cli = { git = "https://github.com/serban300/polkadot-sdk", branch = "polkadot-parachain-lib" }
